version: '2'
services:
  db:
    extends:
      file: ./docker-compose.common.yml
      service: db
  api:
    extends:
      file: ./docker-compose.common.yml
      service: api
    links:
      - db
      - redis
      - elasticsearch
      - test_elasticsearch
    ports:
      - "3001:3000"
    environment:
      REDIS_URL: 'redis://redis:6379'
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      TEST_ELASTICSEARCH_URL: 'http://test_elasticsearch:9200'
  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
  sidekiq:
    extends:
      file: ./docker-compose.common.yml
      service: api
    command: ./bin/sidekiq_start
    links:
      - db
      - redis
      - elasticsearch
      - test_elasticsearch
    environment:
      REDIS_URL: 'redis://redis:6379/0'
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      TEST_ELASTICSEARCH_URL: 'http://test_elasticsearch:9200'
  elasticsearch:
    image: 'elasticsearch:2.4'
  test_elasticsearch:
    image: 'elasticsearch:2.4'
volumes:
  casebook_api_rubygems:

